#!/usr/bin/env python3
"""Re-derive the protocol35 handshake fixture under a synthetic local_key.

The original testdata/handshake/session1.json was a genuine capture and so
embedded a real device's permanent local_key and device_id. This rebuilds an
equivalent fixture around fabricated credentials.

Two properties of the original fixture are deliberately preserved:

  1. The *payloads* are the real ones. Plaintexts are recovered by decrypting
     the captured frames with the real key, then re-encrypted under the fake
     key. So the fixture still exercises genuine device-shaped DP traffic.

  2. The crypto here is an independent implementation (python-cryptography),
     not a call into the Go package under test. The Go tests therefore still
     validate against a second implementation rather than against themselves,
     which was the whole point of the hardware capture.
"""

import binascii
import json
import hashlib
import hmac
import sys
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

PREFIX = 0x00006699
SUFFIX = 0x00009966
IV_LEN = 12
TAG_LEN = 16
NONCE_LEN = 16


def aad_of(seqno: int, cmd: int, length: int) -> bytes:
    return b"\x00\x00" + seqno.to_bytes(4, "big") + cmd.to_bytes(4, "big") + length.to_bytes(4, "big")


def encode(key: bytes, iv: bytes, seqno: int, cmd: int, plaintext: bytes) -> bytes:
    assert len(iv) == IV_LEN, len(iv)
    length = len(plaintext) + IV_LEN + TAG_LEN
    aad = aad_of(seqno, cmd, length)
    ct = AESGCM(key).encrypt(iv, plaintext, aad)  # ciphertext || tag
    return PREFIX.to_bytes(4, "big") + aad + iv + ct + SUFFIX.to_bytes(4, "big")


def decode(key: bytes, frame: bytes):
    assert int.from_bytes(frame[0:4], "big") == PREFIX
    aad = frame[4:18]
    seqno = int.from_bytes(aad[2:6], "big")
    cmd = int.from_bytes(aad[6:10], "big")
    length = int.from_bytes(aad[10:14], "big")
    body = frame[18:18 + length]
    assert int.from_bytes(frame[18 + length:18 + length + 4], "big") == SUFFIX
    iv, ct = body[:IV_LEN], body[IV_LEN:]
    pt = AESGCM(key).decrypt(iv, ct, aad)
    return seqno, cmd, iv, pt


def derive_session_key(local_key: bytes, local_nonce: bytes, remote_nonce: bytes) -> bytes:
    xored = bytes(a ^ b for a, b in zip(local_nonce, remote_nonce))
    sealed = AESGCM(local_key).encrypt(local_nonce[:IV_LEN], xored, None)
    return sealed[:NONCE_LEN]


def main() -> int:
    src, dst = sys.argv[1], sys.argv[2]
    old = json.load(open(src))

    real_key = old["local_key"].encode()
    local_nonce = old["local_nonce"].encode()

    # --- recover the real plaintexts (payloads carry DP data, no credentials)
    real_session_key = derive_session_key(real_key, local_nonce, old["remote_nonce"].encode())
    assert real_session_key.hex() == old["session_key_hex"], "session key derivation drift"

    _, _, _, step2_pt = decode(real_key, binascii.unhexlify(old["frame_step2_hex"]))
    req_seq, req_cmd, _, req_pt = decode(real_session_key, binascii.unhexlify(old["frame_dpquery_req_hex"]))
    resp_seq, resp_cmd, _, resp_pt = decode(
        real_session_key, binascii.unhexlify(old["frame_dpquery_resp_hex"])
    )
    step2_seq, step2_cmd, _, _ = decode(real_key, binascii.unhexlify(old["frame_step2_hex"]))
    s1_seq, s1_cmd, s1_iv, _ = decode(real_key, binascii.unhexlify(old["frame_step1_hex"]))
    s3_seq, s3_cmd, s3_iv, _ = decode(real_key, binascii.unhexlify(old["frame_step3_hex"]))

    assert resp_pt[4:].decode() == old["frame_dpquery_resp_plaintext"], "resp plaintext drift"

    # --- synthetic credentials
    fake_key = b"fake-local-key16"
    assert len(fake_key) == 16
    remote_nonce = b"fedcba9876543210"
    # device-chosen IVs in the original capture; pick fixed synthetic ones
    step2_iv = bytes.fromhex("aabbccddeeff001122334455")[:IV_LEN]
    resp_iv = bytes.fromhex("112233445566778899aabbcc")[:IV_LEN]

    session_key = derive_session_key(fake_key, local_nonce, remote_nonce)

    # step2 payload: retcode(4) || remote_nonce(16) || HMAC(local_key, local_nonce)(32)
    step2_payload = (
        b"\x00\x00\x00\x00"
        + remote_nonce
        + hmac.new(fake_key, local_nonce, hashlib.sha256).digest()
    )
    assert len(step2_payload) == len(step2_pt), (len(step2_payload), len(step2_pt))

    new = dict(old)
    new["_comment"] = (
        "Synthetic handshake vectors for protocol v3.5. Shaped exactly like a real "
        "capture (the DP payloads are the genuine ones recorded against an A60TY10W "
        "on 2026-09-10) but rebuilt around a fabricated local_key, device_id and "
        "remote_nonce so no real device credential is committed. local_nonce is the "
        "fixed value tinytuya emits in debug mode, which keeps both sides of the "
        "handshake reproducible and diffable. Every field below was generated by an "
        "independent Python implementation using the `cryptography` package, NOT by "
        "this Go package -- so the tests that consume this file still check Go "
        "against a second implementation rather than against itself."
    )
    new["local_key"] = fake_key.decode()
    new["remote_nonce"] = remote_nonce.decode()
    new["session_key_hex"] = session_key.hex()
    new["frame_step1_hex"] = encode(fake_key, s1_iv, s1_seq, s1_cmd, local_nonce).hex()
    new["frame_step2_hex"] = encode(fake_key, step2_iv, step2_seq, step2_cmd, step2_payload).hex()
    new["frame_step3_hex"] = encode(
        fake_key, s3_iv, s3_seq, s3_cmd,
        hmac.new(fake_key, remote_nonce, hashlib.sha256).digest(),
    ).hex()
    new["frame_dpquery_req_hex"] = encode(session_key, s1_iv, req_seq, req_cmd, req_pt).hex()
    new["frame_dpquery_resp_hex"] = encode(session_key, resp_iv, resp_seq, resp_cmd, resp_pt).hex()

    with open(dst, "w") as fh:
        json.dump(new, fh, indent=2)
        fh.write("\n")
    print(f"wrote {dst}")
    print(f"  local_key   {fake_key.decode()}")
    print(f"  session_key {session_key.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
